# Generated by Django 5.2.6 on 2025-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_aichat_aimessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Профиль завершен'),
        ),
    ]
