# Generated by Django 5.2.6 on 2025-10-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_groupchat_groupmessage_studygroup_groupchat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель')], default='student', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
