# Generated by Django 5.2.6 on 2025-10-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_promocode_subscription_payment'),
    ]

    operations = [
    ]
