# Generated by Django 6.0 on 2025-12-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20251021_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='Список вопросов с ответами пользователя', verbose_name='Вопросы теста')),
                ('answers', models.JSONField(default=list, verbose_name='Ответы пользователя')),
                ('ai_analysis', models.JSONField(blank=True, null=True, verbose_name='Анализ AI')),
                ('detected_level', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2, null=True, verbose_name='Определенный уровень')),
                ('recommended_topics', models.JSONField(default=list, verbose_name='Рекомендуемые темы')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Балл')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальный балл')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест уровня языка',
                'verbose_name_plural': 'Тесты уровня языка',
                'ordering': ['-created_at'],
            },
        ),
    ]
