# Generated by Django 6.0 on 2025-12-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_languageleveltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageleveltest',
            name='answers',
            field=models.JSONField(blank=True, default=list, verbose_name='Ответы пользователя'),
        ),
        migrations.AlterField(
            model_name='languageleveltest',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text='Список вопросов с ответами пользователя', null=True, verbose_name='Вопросы теста'),
        ),
        migrations.AlterField(
            model_name='languageleveltest',
            name='recommended_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='Рекомендуемые темы'),
        ),
    ]
