# Generated by Django 4.2.20 on 2025-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модуля')),
                ('description_module', models.CharField(max_length=500, verbose_name='Описание модуля')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='modules/', verbose_name='Фото модуля')),
                ('status', models.CharField(choices=[('Публичный доступ', 'Публичный доступ'), ('Частный доступ', 'Частный доступ')], default='Публичный доступ', max_length=25, verbose_name='Статус публичности')),
                ('password_status', models.CharField(default=None, max_length=10, verbose_name='пароль для частного доступа')),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='B1', max_length=10, verbose_name='Уровень модуля')),
            ],
        ),
    ]
