# Generated by Django 4.2.20 on 2025-04-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='password_status',
            field=models.CharField(default=None, max_length=10, verbose_name='Пароль для частного доступа'),
        ),
        migrations.CreateModel(
            name='TaskBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Listening', 'Listening'), ('Writing', 'Writing'), ('Grammar', 'Grammar'), ('Reading', 'Reading'), ('Speaking', 'Speaking'), ('Words', 'Words')], max_length=20, verbose_name='Тип блока')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_blocks', to='modules.module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('task_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='modules.taskblock', verbose_name='Блок заданий')),
            ],
        ),
    ]
