# Generated by Django 4.2.20 on 2025-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_password_status_taskblock_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prompt',
            field=models.TextField(default=1, verbose_name='Неправильное или условное предложение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('fill_in_the_blank', 'Заполнить пропуск'), ('match', 'Соединить элементы'), ('correct_sentence', 'Исправить предложение'), ('choose_correct', 'Выбрать правильный вариант'), ('rewrite', 'Переписать'), ('transform_verb', 'Изменить глагол'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип задания'),
        ),
        migrations.AlterField(
            model_name='module',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='modules_photo/', verbose_name='Фото модуля'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание задания / инструкция'),
        ),
    ]
