# Generated by Django 4.2.20 on 2025-04-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_task_correct_answer_taskoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='media_audio',
            field=models.FileField(blank=True, null=True, upload_to='task_media/audio/', verbose_name='Аудио к заданию'),
        ),
        migrations.AddField(
            model_name='task',
            name='media_image',
            field=models.ImageField(blank=True, null=True, upload_to='task_media/images/', verbose_name='Изображение к заданию'),
        ),
        migrations.AddField(
            model_name='taskoption',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='option_media/audio/', verbose_name='Аудио варианта'),
        ),
        migrations.AddField(
            model_name='taskoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='option_media/images/', verbose_name='Изображение варианта'),
        ),
        migrations.AlterField(
            model_name='taskoption',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант ответа'),
        ),
    ]
