# Generated by Django 5.2.6 on 2025-09-13 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_task_media_audio_task_media_image_taskoption_audio_and_more'),
        ('study_modules', '0005_unit_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='study_modules.topic', verbose_name='Тема'),
        ),
    ]
