# Generated by Django 6.0 on 2025-12-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='text_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='text_check.textcheck'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='themes', to='text_check.error'),
        ),
    ]
