# Generated by Django 4.2.21 on 2025-05-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_module_description_learningprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BubbleGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.IntegerField(help_text='Время прохождения в секундах')),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_records', to='cards.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_seconds'],
                'indexes': [models.Index(fields=['user', 'module'], name='cards_bubbl_user_id_b1451a_idx')],
            },
        ),
    ]
