# Generated by Django 4.2.21 on 2025-05-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def remove_duplicates(apps, schema_editor):
    BubbleGameRecord = apps.get_model('cards', 'BubbleGameRecord')
    
    # Получаем все записи, сгруппированные по user_id и module_id
    duplicates = (
        BubbleGameRecord.objects
        .values('user_id', 'module_id')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
    )
    
    # Для каждой группы дубликатов оставляем только одну запись (с максимальным correct_answers)
    for duplicate in duplicates:
        records = (
            BubbleGameRecord.objects
            .filter(
                user_id=duplicate['user_id'],
                module_id=duplicate['module_id']
            )
            .order_by('-correct_answers')
        )
        
        # Получаем ID записи с максимальным значением correct_answers
        best_record_id = records.first().id
        
        # Удаляем все остальные записи
        BubbleGameRecord.objects.filter(
            user_id=duplicate['user_id'],
            module_id=duplicate['module_id']
        ).exclude(id=best_record_id).delete()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_bubblegamerecord'),
    ]

    operations = [
        # Сначала создаем новую модель
        migrations.CreateModel(
            name='BalloonGameRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рекорд игры "Воздушные шары"',
                'verbose_name_plural': 'Рекорды игры "Воздушные шары"',
                'unique_together': {('user', 'module')},
            },
        ),
        # Изменяем опции модели BubbleGameRecord
        migrations.AlterModelOptions(
            name='bubblegamerecord',
            options={'verbose_name': 'Рекорд игры "Пузыри"', 'verbose_name_plural': 'Рекорды игры "Пузыри"'},
        ),
        # Удаляем старый индекс
        migrations.RemoveIndex(
            model_name='bubblegamerecord',
            name='cards_bubbl_user_id_b1451a_idx',
        ),
        # Удаляем дубликаты перед изменением полей
        migrations.RunPython(remove_duplicates),
        # Переименовываем поле
        migrations.RenameField(
            model_name='bubblegamerecord',
            old_name='correct_answers',
            new_name='score',
        ),
        # Добавляем новые поля и ограничения
        migrations.AddField(
            model_name='bubblegamerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='bubblegamerecord',
            unique_together={('user', 'module')},
        ),
        migrations.RemoveField(
            model_name='bubblegamerecord',
            name='incorrect_answers',
        ),
        migrations.RemoveField(
            model_name='bubblegamerecord',
            name='time_seconds',
        ),
    ]
