# Generated by Django 5.2.6 on 2025-09-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_module_saved_by_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bubblegamerecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='module',
            name='saved_by_users',
        ),
        migrations.AddField(
            model_name='module',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
