# Generated by Django 4.2.10 on 2025-05-09 18:35

from django.db import migrations, models
import study_modules.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymodule',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1200x800 пикселей', null=True, upload_to=study_modules.models.module_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='studymodule',
            name='module_type',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('premium', 'Премиум'), ('locked', 'Закрытый')], default='free', max_length=10, verbose_name='Тип модуля'),
        ),
    ]
