# Generated by Django 4.2.10 on 2025-05-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0002_alter_studymodule_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymodule',
            options={'default_manager_name': 'objects', 'ordering': ['-created_at'], 'verbose_name': 'Учебный модуль', 'verbose_name_plural': 'Учебные модули'},
        ),
    ]
