# Generated by Django 5.2.6 on 2025-09-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0003_alter_studymodule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Аудио'), ('doc', 'Документ'), ('image', 'Изображение'), ('video', 'Видео'), ('other', 'Другое')], max_length=10, verbose_name='Тип файла')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='module_attachments/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание файла')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='Размер файла')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='study_modules.studymodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('theory', 'Теоретическая часть'), ('practice', 'Практическая часть')], max_length=10, verbose_name='Тип секции')),
                ('title', models.CharField(max_length=200, verbose_name='Название секции')),
                ('description', models.TextField(blank=True, verbose_name='Описание секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='study_modules.studymodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Секция модуля',
                'verbose_name_plural': 'Секции модулей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('listening', 'Listening'), ('writing', 'Writing'), ('grammar', 'Grammar'), ('reading', 'Reading'), ('speaking', 'Speaking'), ('words', 'Words'), ('watching', 'Watching'), ('test', 'Test')], max_length=20, verbose_name='Тип навыка')),
                ('title', models.CharField(max_length=200, verbose_name='Название навыка')),
                ('description', models.TextField(blank=True, verbose_name='Описание навыка')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='study_modules.studymodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Навык модуля',
                'verbose_name_plural': 'Навыки модулей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TheoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название карточки')),
                ('content', models.TextField(blank=True, verbose_name='Содержание карточки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_cards', to='study_modules.modulesection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Теоретическая карточка',
                'verbose_name_plural': 'Теоретические карточки',
                'ordering': ['order'],
            },
        ),
    ]
