# Generated by Django 4.2.10 on 2025-09-13 08:53

from django.db import migrations, models
import django.db.models.deletion
import study_modules.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0004_moduleattachment_modulesection_moduleskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название юнита')),
                ('description', models.TextField(blank=True, verbose_name='Описание юнита')),
                ('image', models.ImageField(blank=True, null=True, upload_to=study_modules.models.unit_image_path, verbose_name='Изображение юнита')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='study_modules.studymodule', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Юнит',
                'verbose_name_plural': 'Юниты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('theory_content', models.TextField(blank=True, verbose_name='Теоретическая часть')),
                ('practice_content', models.TextField(blank=True, verbose_name='Практическая часть')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='study_modules.unit', verbose_name='Юнит')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['order'],
            },
        ),
    ]
