# Generated by Django 5.2.6 on 2025-09-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_bubblegamerecord_options_and_more'),
        ('study_modules', '0005_unit_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('card_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to_study_modules', to='cards.module', verbose_name='Модуль карточек')),
                ('study_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_card_modules', to='study_modules.studymodule', verbose_name='Учебный модуль')),
            ],
            options={
                'verbose_name': 'Прикрепленный модуль карточек',
                'verbose_name_plural': 'Прикрепленные модули карточек',
                'ordering': ['order'],
                'unique_together': {('study_module', 'card_module')},
            },
        ),
    ]
