# Generated by Django 5.2.6 on 2025-09-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0007_unitattachment_unitsection_unitskill_unittheorycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('matching', 'Соединение слов'), ('sentence_rewrite', 'Переписывание предложений'), ('translation_choice', 'Выбор перевода'), ('sentence_builder', 'Составление предложений')], max_length=20, verbose_name='Тип задания')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('instruction', models.TextField(verbose_name='Инструкция')),
                ('content', models.JSONField(verbose_name='Содержание задания')),
                ('correct_answer', models.JSONField(verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_tasks', to='study_modules.unitskill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Задание грамматики',
                'verbose_name_plural': 'Задания грамматики',
                'ordering': ['order'],
            },
        ),
    ]
