# Generated by Django 5.2.6 on 2025-10-04 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0008_grammartask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('correct_attempts', models.PositiveIntegerField(default=0, verbose_name='Правильных попыток')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Последняя попытка')),
                ('best_score', models.FloatField(default=0.0, verbose_name='Лучший результат')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_modules.grammartask', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по заданию',
                'verbose_name_plural': 'Прогресс по заданиям',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
