# Generated by Django 5.2.6 on 2025-10-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_modules', '0009_usertaskprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodule',
            name='access_password',
            field=models.CharField(blank=True, help_text='Пароль для доступа к закрытому модулю', max_length=255, null=True, verbose_name='Пароль доступа'),
        ),
        migrations.CreateModel(
            name='ModuleAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('message', models.TextField(blank=True, help_text='Описание почему нужен доступ', verbose_name='Сообщение от пользователя')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('reviewer_message', models.TextField(blank=True, verbose_name='Комментарий рассмотревшего')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='study_modules.studymodule', verbose_name='Модуль')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Рассмотревший')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на доступ к модулю',
                'verbose_name_plural': 'Заявки на доступ к модулям',
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('request', 'Через заявку'), ('password', 'Через пароль'), ('author', 'Автор модуля')], max_length=20, verbose_name='Тип доступа')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения доступа')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='study_modules.studymodule', verbose_name='Модуль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя к модулю',
                'verbose_name_plural': 'Доступы пользователей к модулям',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
