"""
Django settings for engai project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6h^6q$yr$q4=x%asd*ul$m$4d*cmu$cbe)h9n7ycu5x4)@bgbd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Добавляем sites
    'modules',
    'users',
    'dictionary',
    'cards.apps.CardsConfig',  # Изменено с 'cards' на полный путь
    'social_django',  # Добавляем приложение для социальной аутентификации
    'study_modules',  # Добавляем новое приложение
    'rest_framework',  # Добавляем DRF
    'notifications',  # Добавляем приложение уведомлений
    'channels',
    'text_check',
    'deadlines',  # Добавляем приложение дедлайнов
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # Добавляем middleware
    'users.middleware.ProfileCompletionMiddleware',  # Проверка заполненности профиля
]

ROOT_URLCONF = 'engai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Добавляем путь к общим шаблонам
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # Добавляем для social_django
                'social_django.context_processors.login_redirect',  # Добавляем для social_django
            ],
        },
    },
]

WSGI_APPLICATION = 'engai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Общие статические файлы
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # или другой SMTP-сервер
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your-email@gmail.com'  # замените на ваш email
EMAIL_HOST_PASSWORD = 'your-app-password'  # замените на пароль приложения

# Site settings
SITE_ID = 1

# Настройки аутентификации
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',  # Бэкенд для Google
    'social_core.backends.github.GithubOAuth2',  # Бэкенд для GitHub
    'social_core.backends.apple.AppleIdAuth',  # Бэкенд для Apple
    'django.contrib.auth.backends.ModelBackend',  # Стандартный бэкенд Django
)

# Настройки для Google OAuth2
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'ваш_google_client_id'  # Замените на ваш Google Client ID
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'ваш_google_client_secret'  # Замените на ваш Google Client Secret
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'openid',
    'email',
    'profile',
]

# Настройки для GitHub OAuth2
SOCIAL_AUTH_GITHUB_KEY = 'Ov23liUvozZ5Be8eQGYF'  # GitHub Client ID
SOCIAL_AUTH_GITHUB_SECRET = 'c4cdd29c73620bbd2b4c96c3e42c111f3eefcb60'  # GitHub Client Secret
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

# Настройки для Apple Sign In
SOCIAL_AUTH_APPLE_ID_CLIENT = 'ваш_apple_service_id'  # Service ID из Apple Developer
SOCIAL_AUTH_APPLE_ID_TEAM = 'ваш_apple_team_id'  # Team ID из Apple Developer
SOCIAL_AUTH_APPLE_ID_KEY = 'ваш_apple_key_id'  # Key ID из Apple Developer
SOCIAL_AUTH_APPLE_ID_SECRET = 'ваш_apple_private_key'  # Private Key (.p8 файл)
SOCIAL_AUTH_APPLE_ID_SCOPE = ['email', 'name']
SOCIAL_AUTH_APPLE_ID_EMAIL_AS_USERNAME = True

# Настройки для социальной аутентификации
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Настройки для сохранения данных пользователя
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'users.pipeline.associate_by_email',  # Кастомная функция для связывания по email
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'users.pipeline.create_user_profile',  # Кастомная функция для заполнения профиля
)

# Channels
ASGI_APPLICATION = 'engai.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# Mistral AI settings
MISTRAL_API_KEY = '0A5W69RwK9MujYvIHldRXUihWehJKM7M'

# Настройки безопасности для загрузки файлов
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Настройки для кастомных страниц ошибок
# Для включения кастомных страниц ошибок в production установите DEBUG = False
# В режиме разработки для тестирования 404 используйте URL: /404-test/
USE_CUSTOM_ERROR_PAGES = True
FILE_UPLOAD_PERMISSIONS = 0o644

# Разрешенные типы файлов для загрузки
ALLOWED_FILE_EXTENSIONS = {
    'images': ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp'],
    'documents': ['.pdf', '.doc', '.docx', '.txt'],
    'archives': ['.zip', '.rar']
}

# Максимальный размер файла для каждого типа (в байтах)
MAX_FILE_SIZES = {
    'images': 5 * 1024 * 1024,  # 5MB для изображений
    'documents': 10 * 1024 * 1024,  # 10MB для документов
    'archives': 10 * 1024 * 1024,  # 10MB для архивов
}

# Настройки безопасности
SECURE_FILE_UPLOAD = True
SCAN_UPLOADED_FILES = True  # В будущем можно добавить антивирусное сканирование
