# Generated by Django 4.2.10 on 2025-05-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('achievement', 'Достижение'), ('message', 'Сообщение'), ('update', 'Обновление')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
